apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../argocd/overlays/production
- ingress-argocd-server.yaml
- secret-ipd-ca.yaml
patchesStrategicMerge:
- patch-argocd-cm.yaml
- patch-argocd-dex-server.yaml
- patch-argocd-tls-certs-cm.yaml
namespace: argocd
