apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-oauth2-proxy-resources" .HostCluster.Name}}
  namespace: argocd
spec:
  project: {{.HostCluster.ArgocdProject}}
  source:
    path: host-clusters/{{.HostCluster.Name}}/oauth2-proxy/overlays/production
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
  destination:
    server: {{.HostCluster.ApiServer}}
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
