apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{printf "%s-traefik-resources" .HostCluster.Name}}
  namespace: argocd
spec:
  project: {{.HostCluster.ArgocdProject}}
  source:
    path: host-clusters/{{.HostCluster.Name}}/traefik/overlays/production
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
  destination:
    server: {{.HostCluster.ApiServer}}
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
