apiVersion: v1
data:
  ca.crt: |
  {{- range $line := split .SecretConfigs.Vault.CABundle "\n" }}
    {{ $line | html }}
  {{- end }}
kind: ConfigMap
metadata:
  name: ca-certificates
  namespace: argo-events
